export interface MockupProduct {
  id: string;
  name: string;
  category: string;
  description: string;
  longDescription: string;
  price: number;
  devices: string[];
  promptCount: number;
  previewImage: string;
  buyUrl: string;
  features: string[];
  whatsIncluded: string[];
  techStack: string[];
  sections: { title: string; content: string }[];
  mockupImages: { gradient: string; pageTitle: string; src?: string }[];
}

export const mockupProducts: MockupProduct[] = [
  {
    id: "device-mockup-pack",
    name: "Complete Device Mockup Prompt Pack",
    category: "All Devices",
    description: "500+ AI prompts for generating photorealistic device mockups — laptops, desktops, tablets, phones, and smartwatches.",
    longDescription: "The Complete Device Mockup Prompt Pack gives you 500+ expertly crafted AI prompts for generating stunning, photorealistic device mockups. From MacBook Pros and iMacs to iPhones, iPads, and smartwatches — every device angle, lighting setup, and environment is covered. Works with Midjourney, DALL·E 3, Stable Diffusion, and Leonardo AI.",
    price: 39,
    devices: ["Laptop", "Desktop", "Tablet", "Mobile", "Smartwatch"],
    promptCount: 500,
    previewImage: "https://res.cloudinary.com/dhkyla1rv/image/upload/v1782387442/Ultra-realistic_editorial_product_mockup_photograph_202606152222.jpg",
    buyUrl: "https://payhip.com/b/mockup-pack",
    features: [
      "500+ Premium AI Prompts",
      "Covers 5 Device Categories",
      "Multiple Angles & Environments",
      "Studio & Lifestyle Lighting Setups",
      "Works with Midjourney, DALL·E 3, SD, Leonardo",
      "Instant Download (TXT & PDF)",
      "Free Lifetime Updates",
      "Commercial Use License Included"
    ],
    whatsIncluded: [
      "500+ text prompts in organized categories",
      "Prompt formula guide for custom variations",
      "Device dimension & aspect ratio cheat sheet",
      "Lighting & environment reference guide",
      "Post-processing tips for realistic results"
    ],
    techStack: ["Midjourney", "DALL·E 3", "Stable Diffusion", "Leonardo AI"],
    sections: [
      {
        title: "What Makes This Pack Unique:",
        content: "Every prompt is tested and optimized for photorealism. We include specific camera angles, lighting conditions, and environmental contexts — so your mockups look like they were shot in a professional studio, not generated by AI."
      },
      {
        title: "Commercial License Included:",
        content: "All prompts come with a full commercial use license. Use the generated mockups for client projects, portfolio showcases, social media marketing, and commercial products — no attribution required."
      },
      {
        title: "Works With All Major AI Platforms:",
        content: "Each prompt is formatted and tested across Midjourney v6, DALL·E 3, Stable Diffusion XL, and Leonardo AI. We also include platform-specific optimization tips for each tool."
      }
    ],
    mockupImages: [
      { gradient: "from-slate-900 to-zinc-800", pageTitle: "Laptop Mockup Collection", src: "https://res.cloudinary.com/dhkyla1rv/image/upload/v1782387442/STRICT_RULE__The_laptop_screen_202606151919_1.jpg" },
      { gradient: "from-zinc-100 to-white", pageTitle: "Desktop & iMac Setups", src: "https://res.cloudinary.com/dhkyla1rv/image/upload/v1782387442/GLOBAL_RULES___MOCKUP_IMAGE_202606151917.jpg" },
      { gradient: "from-slate-800 to-zinc-900", pageTitle: "Mobile & Tablet Views", src: "https://res.cloudinary.com/dhkyla1rv/image/upload/v1782387187/Use_the_exact_uploaded_mobile_202606241740_1.jpg" }
    ]
  },
  {
    id: "laptop-mockup-prompts",
    name: "Laptop Mockup Prompt Bundle",
    category: "Laptop",
    description: "150+ AI prompts for photorealistic laptop mockups — MacBook, ThinkPad, Surface, and more in studio & lifestyle settings.",
    longDescription: "The Laptop Mockup Prompt Bundle delivers 150+ meticulously crafted AI prompts for generating professional laptop mockups. Includes MacBook Pro/Air, Dell XPS, ThinkPad, Surface Laptop, and generic laptop silhouettes. Each prompt specifies angle, lighting, environment, and composition for consistent, studio-quality results.",
    price: 19,
    devices: ["Laptop"],
    promptCount: 150,
    previewImage: "https://res.cloudinary.com/dhkyla1rv/image/upload/v1782387442/STRICT_RULE__The_laptop_screen_202606151919_1.jpg",
    buyUrl: "https://payhip.com/b/laptop-prompts",
    features: [
      "150+ Premium Laptop Prompts",
      "MacBook, ThinkPad, Surface & More",
      "Studio & Lifestyle Environments",
      "Top, Front, Isometric & Side Angles",
      "Works with Midjourney, DALL·E 3, SD",
      "Instant Download (TXT & PDF)",
      "Free Lifetime Updates",
      "Commercial Use License"
    ],
    whatsIncluded: [
      "150+ laptop-specific prompts",
      "Angle reference guide (top, front, isometric, side)",
      "Lighting setup cheat sheet",
      "Brand-specific silhouette prompts",
      "Editing & post-processing tips"
    ],
    techStack: ["Midjourney", "DALL·E 3", "Stable Diffusion"],
    sections: [
      {
        title: "Device-Specific Optimization:",
        content: "Each prompt is tailored to specific laptop models and silhouettes — from the iconic MacBook notch to ThinkPad's classic design. Get consistent device proportions every time."
      },
      {
        title: "Ready for Client Work:",
        content: "These prompts are designed to produce portfolio-ready mockups. Combine with your website screenshots for stunning case study presentations, template previews, and social media assets."
      }
    ],
    mockupImages: [
      { gradient: "from-slate-900 to-zinc-800", pageTitle: "MacBook Pro Studio Shot" },
      { gradient: "from-zinc-100 to-white", pageTitle: "Laptop Workspace Setup" },
      { gradient: "from-amber-50 to-stone-200", pageTitle: "Isometric Laptop View" }
    ]
  },
  {
    id: "mobile-mockup-prompts",
    name: "Mobile & Tablet Mockup Prompt Bundle",
    category: "Mobile & Tablet",
    description: "200+ AI prompts for photorealistic smartphone and tablet mockups — iPhone, Galaxy, iPad, and more.",
    longDescription: "The Mobile & Tablet Mockup Prompt Bundle includes 200+ AI prompts for generating stunning smartphone and tablet mockups. Covers iPhone (14/15/16), Samsung Galaxy, Google Pixel, iPad Pro, iPad Air, and Android tablets. Multiple grips, orientations, and environmental contexts included.",
    price: 19,
    devices: ["Mobile", "Tablet"],
    promptCount: 200,
    previewImage: "https://res.cloudinary.com/dhkyla1rv/image/upload/v1782387187/Use_the_exact_uploaded_mobile_202606241740_1.jpg",
    buyUrl: "https://payhip.com/b/mobile-prompts",
    features: [
      "200+ Mobile & Tablet Prompts",
      "iPhone, Galaxy, Pixel & iPad",
      "Portrait & Landscape Orientations",
      "Hand Grip & Standalone Setups",
      "Works with Midjourney, DALL·E 3, SD",
      "Instant Download (TXT & PDF)",
      "Free Lifetime Updates",
      "Commercial Use License"
    ],
    whatsIncluded: [
      "200+ mobile & tablet-specific prompts",
      "Device dimension reference sheet",
      "Hand grip composition guide",
      "Screen reflection & lighting tips",
      "Social media optimized aspect ratios"
    ],
    techStack: ["Midjourney", "DALL·E 3", "Stable Diffusion", "Leonardo AI"],
    sections: [
      {
        title: "Perfect for App & Web Previews:",
        content: "Generate mockups that showcase your app, website, or template on the most popular mobile and tablet devices. Each prompt is optimized for screen clarity and realistic reflections."
      },
      {
        title: "Multiple Viewing Angles:",
        content: "Includes front-facing, tilted, hand-held, and flat-lay compositions. Perfect for app store screenshots, social media promotions, and portfolio presentations."
      }
    ],
    mockupImages: [
      { gradient: "from-zinc-950 via-slate-900 to-black", pageTitle: "iPhone Hand Grip Shot" },
      { gradient: "from-slate-100 to-white", pageTitle: "iPad Flat Lay Setup" },
      { gradient: "from-stone-900 to-zinc-800", pageTitle: "Samsung Galaxy Display" }
    ]
  },
  {
    id: "desktop-mockup-prompts",
    name: "Desktop & Monitor Mockup Prompt Bundle",
    category: "Desktop",
    description: "120+ AI prompts for photorealistic desktop and monitor mockups — iMac, ultra-wide, dual-monitor setups & more.",
    longDescription: "The Desktop & Monitor Mockup Prompt Bundle delivers 120+ AI prompts for generating professional desktop and monitor mockups. Includes iMac, Dell UltraSharp, Samsung Odyssey ultra-wide, dual-monitor setups, and standing desk configurations. Perfect for showcasing software, dashboards, and creative portfolios.",
    price: 19,
    devices: ["Desktop", "Monitor"],
    promptCount: 120,
    previewImage: "https://res.cloudinary.com/dhkyla1rv/image/upload/v1782387442/GLOBAL_RULES___MOCKUP_IMAGE_202606151917.jpg",
    buyUrl: "https://payhip.com/b/desktop-prompts",
    features: [
      "120+ Desktop & Monitor Prompts",
      "iMac, Ultra-wide & Dual-Monitor",
      "Studio & Office Environments",
      "Multiple Monitor Angles",
      "Works with Midjourney, DALL·E 3, SD",
      "Instant Download (TXT & PDF)",
      "Free Lifetime Updates",
      "Commercial Use License"
    ],
    whatsIncluded: [
      "120+ desktop & monitor-specific prompts",
      "Dual & triple monitor setup configurations",
      "Office & studio environment descriptions",
      "Cable management & clean desk aesthetics",
      "Resolution & aspect ratio reference guide"
    ],
    techStack: ["Midjourney", "DALL·E 3", "Stable Diffusion"],
    sections: [
      {
        title: "Showcase Your Dashboard & Data:",
        content: "Ideal for SaaS companies, data analytics platforms, and creative studios. Generate mockups that make your dashboard, portfolio, or design work look stunning on large screens."
      },
      {
        title: "Professional Environment Contexts:",
        content: "Choose from minimal studio setups, modern office environments, or creative workspace contexts. Every prompt specifies lighting, depth of field, and color grading for consistent results."
      }
    ],
    mockupImages: [
      { gradient: "from-slate-800 to-zinc-900", pageTitle: "Ultra-wide Monitor Setup" },
      { gradient: "from-zinc-50 to-white", pageTitle: "Minimal iMac Studio" },
      { gradient: "from-amber-50 to-orange-100", pageTitle: "Dual Monitor Workspace" }
    ]
  },
  {
    id: "social-mockup-prompts",
    name: "Social Media Mockup Scene Bundle",
    category: "Social Media",
    description: "180+ AI prompts for social-media-ready device mockup scenes — Instagram, TikTok, LinkedIn, and portfolio formats.",
    longDescription: "The Social Media Mockup Scene Bundle provides 180+ AI prompts designed specifically for social media content creators. Generate scroll-stopping device mockups optimized for Instagram posts, TikTok videos, LinkedIn banners, and portfolio showcases. Every prompt includes platform-specific aspect ratios and composition guidelines.",
    price: 29,
    devices: ["Laptop", "Mobile", "Tablet", "Desktop"],
    promptCount: 180,
    previewImage: "https://res.cloudinary.com/dhkyla1rv/image/upload/v1782387187/Hyperrealistic_CGI_product_photography__Octane_202606241215_2.jpg",
    buyUrl: "https://payhip.com/b/social-prompts",
    features: [
      "180+ Social-Media-Optimized Prompts",
      "Instagram, TikTok, LinkedIn & Portfolio Formats",
      "Multi-Device Scene Compositions",
      "Platform-Specific Aspect Ratios",
      "Works with Midjourney, DALL·E 3, SD",
      "Instant Download (TXT & PDF)",
      "Free Lifetime Updates",
      "Commercial Use License"
    ],
    whatsIncluded: [
      "180+ social-media-optimized prompts",
      "Platform aspect ratio cheat sheet",
      "Multi-device scene composition guide",
      "Caption & hashtag template pack",
      "Post-processing for social media formats"
    ],
    techStack: ["Midjourney", "DALL·E 3", "Stable Diffusion", "Leonardo AI"],
    sections: [
      {
        title: "Designed for Social Media Impact:",
        content: "Each prompt is crafted to produce images that stop the scroll. Includes multi-device scenes (laptop + phone + tablet), flat lays, and creative device arrangements optimized for social feeds."
      },
      {
        title: "Platform-Ready Formats:",
        content: "All prompts include aspect ratio guidance for Instagram (1:1, 4:5), TikTok (9:16), LinkedIn (1.91:1), and portfolio presentations (16:9). No cropping needed — your mockups fit perfectly."
      }
    ],
    mockupImages: [
      { gradient: "from-violet-900 to-zinc-900", pageTitle: "Instagram Multi-Device Scene" },
      { gradient: "from-zinc-50 to-violet-100", pageTitle: "LinkedIn Banner Setup" },
      { gradient: "from-slate-900 to-zinc-800", pageTitle: "TikTok Product Showcase" }
    ]
  }
];
